### ISSUE TITLE
Semantics of `RandomCrop`

### ISSUE THREAD

**Issue by samuela** [khdlr/augmax#6]
I have a few questions that AFAIU are not covered in the documentation,
* What happens if the requested width/height are larger than the input image?
* If the requested width/height is less than the input image, will the returned image lie outside the strict borders of the input? If so, what sort of padding is done?
* If the requested width/height are exactly equal to the input image, does it reduce to the identity function?

I also consulted the albumentations API docs, but they didn't have much more information. So just putting these questions out into the ether...

**Comment by khdlr** [comment]
You're right, documentation is lacking on many ends currently - I'm currently doing a rewrite of the Geometric Transforms that will enable some cool features like dynamic ops fusion and invertible augmentations (which I currently need for a project... :smile:), so I didn't spend too much time documenting the old code.

Here are the current (v0.2.2) semantics:
* `RandomCrop` aligns the image toward the top-left of the image for requested dimensions that exceed the true image size (I hope it becomes a bit clearer from the image below)
![image](https://user-images.githubusercontent.com/9249838/155287770-33127de5-39da-4fd0-971f-af16c068e3e2.png) ` -> RandomCrop(300, 100) -> `  ![image](https://user-images.githubusercontent.com/9249838/155287779-ff81d41d-9e35-4084-acab-b15dc85ac96b.png)
* When `RandomCrop`ing to a size that is smaller than (or equal to) the original image size, the crop lies within the borders of the input image without additional padding. However, interactions with other Transformations (e.g. Rotations) can change that. In these cases, zero-padding is currently used, which I plan to make configurable in the future (cf. the black triangle in the output below).
![image](https://user-images.githubusercontent.com/9249838/155287770-33127de5-39da-4fd0-971f-af16c068e3e2.png) `->  Rotate() -> RandomCrop(100) ->` ![image](https://user-images.githubusercontent.com/9249838/155289262-1e69261a-9afd-4d48-af0b-f1c7c843f4ae.png)
* Yes, for `input_size == output_size`, `RandomCrop` becomes the identity function.

Re your first point: In the future, Crops and Pads will share the same code path, so that `RandomCrop`ing to a larger canvas size will behave like a "RandomPadding" operation that places the input image somewhere within the original Canvas.

**Comment by samuela** [comment]
Thanks so much for your detailed explanation @khdlr! In order to achieve the "random crop with padding" pattern, is there a pad operation?

**Comment by PythonNut** [comment]
I think you might be able to do something like "pad then random crop" by chaining `CenterCrop` with a larger output size (reflecting the padding) followed by `RandomCrop`. As far as I can tell, this results in outputs resembling `padding_mode = "edge"` (in `torchvision` terms), although the images above made me expect zero padding so I'm a bit confused.
